[project]
name = "company"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pypdf>=6.7.4",
    "reportlab>=4.4.10",
    "streamlit>=1.54.0",
]
